spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/study2?serverTimezone=UTC

mybatis:
  config-location: classpath:mybatis-config.xml # mybatis配置文件的路径
  mapper-locations: classpath:mapper/*.xml # mapper XML路径
  type-aliases-package: com.entity

